# -*- coding: utf-8 -*-
"""
Calculation report for EarthWorkQ.

The report is the deliverable.  It records every input, every assumption and
every quality check, so that a reviewer can decide whether to trust the number
without re-running the calculation.  A quantity issued without its cell size,
its interpolation method and its cross-validation error is not a quantity, it
is a guess with decimal places.
"""

from __future__ import annotations

import base64
import datetime
import html
import os

from .sources import QualityIssue

CSS = """
:root { --ink:#1b1b1b; --muted:#666; --rule:#d8d8d8; --cut:#c0392b;
        --fill:#1f5fa9; --ok:#27682a; --warn:#b26a00; --err:#a4161a; }
* { box-sizing: border-box; }
body { font-family: -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
       color: var(--ink); margin: 0; padding: 32px 40px 64px; line-height: 1.5;
       max-width: 1000px; }
h1 { font-size: 26px; margin: 0 0 4px; letter-spacing: -0.2px; }
h2 { font-size: 17px; margin: 34px 0 10px; padding-bottom: 6px;
     border-bottom: 2px solid var(--ink); text-transform: uppercase;
     letter-spacing: 0.06em; }
h3 { font-size: 14px; margin: 20px 0 6px; color: var(--muted);
     text-transform: uppercase; letter-spacing: 0.05em; }
.sub { color: var(--muted); font-size: 13px; margin-bottom: 4px; }
table { border-collapse: collapse; width: 100%; margin: 8px 0 14px;
        font-size: 13px; }
th, td { text-align: left; padding: 6px 10px; border-bottom: 1px solid var(--rule); }
th { background: #f4f4f4; font-weight: 600; }
td.num, th.num { text-align: right; font-variant-numeric: tabular-nums; }
tr.total td { font-weight: 700; border-top: 2px solid var(--ink);
              border-bottom: 2px solid var(--ink); }
.kpi { display: flex; gap: 14px; flex-wrap: wrap; margin: 14px 0 6px; }
.card { flex: 1 1 170px; border: 1px solid var(--rule); border-radius: 8px;
        padding: 12px 14px; }
.card .label { font-size: 11px; text-transform: uppercase; color: var(--muted);
               letter-spacing: 0.06em; }
.card .value { font-size: 21px; font-weight: 700; font-variant-numeric: tabular-nums; }
.card .unit { font-size: 12px; color: var(--muted); }
.card.cut .value { color: var(--cut); }
.card.fill .value { color: var(--fill); }
.card.net .value { color: var(--ok); }
.issue { border-left: 4px solid var(--rule); padding: 8px 12px; margin: 6px 0;
         background: #fafafa; font-size: 13px; }
.issue.warning { border-left-color: var(--warn); }
.issue.error { border-left-color: var(--err); }
.issue.info { border-left-color: #4a7fb5; }
.issue .tag { font-weight: 700; text-transform: uppercase; font-size: 11px;
              letter-spacing: 0.06em; margin-right: 8px; }
.issue.warning .tag { color: var(--warn); }
.issue.error .tag { color: var(--err); }
.issue.info .tag { color: #4a7fb5; }
img.chart { width: 100%; border: 1px solid var(--rule); border-radius: 6px;
            margin: 10px 0; }
.foot { margin-top: 40px; padding-top: 12px; border-top: 1px solid var(--rule);
        font-size: 11px; color: var(--muted); }
code { background: #f2f2f2; padding: 1px 5px; border-radius: 3px; font-size: 12px; }
"""


def _e(v):
    return html.escape(str(v))


def _num(v, dp=2):
    try:
        return "{:,.{dp}f}".format(float(v), dp=dp)
    except (TypeError, ValueError):
        return "-"


def _rows_table(rows, headers=("Item", "Value")):
    out = ["<table><thead><tr>%s</tr></thead><tbody>"
           % "".join("<th>%s</th>" % _e(h) for h in headers)]
    for r in rows:
        out.append("<tr>%s</tr>" % "".join("<td>%s</td>" % _e(c) for c in r))
    out.append("</tbody></table>")
    return "".join(out)


def _embed_image(path):
    try:
        with open(path, "rb") as fh:
            data = base64.b64encode(fh.read()).decode("ascii")
        return '<img class="chart" src="data:image/png;base64,%s" alt="chart">' % data
    except Exception:
        return ""


def build_report(result, analysis, project_name=None, prepared_by=None,
                 notes=None, embed_charts=True):
    u = result.unit
    total = result.total
    soil = analysis.soil
    now = datetime.datetime.now().strftime("%d %B %Y at %H:%M")

    parts = []
    parts.append("<!DOCTYPE html><html><head><meta charset='utf-8'>")
    parts.append("<title>EarthWorkQ calculation report</title>")
    parts.append("<style>%s</style></head><body>" % CSS)

    parts.append("<h1>Earthwork quantity calculation</h1>")
    parts.append("<div class='sub'>%s</div>"
                 % _e(project_name or analysis.aoi_layer.name()))
    parts.append("<div class='sub'>Generated by EarthWorkQ on %s%s</div>"
                 % (_e(now), " &middot; prepared by %s" % _e(prepared_by)
                    if prepared_by else ""))

    # ---------------- headline ----------------
    parts.append("<h2>Quantities</h2>")
    net = total.net if soil is None else total.net_after_shrinkage(soil)
    parts.append("<div class='kpi'>")
    parts.append(_card("Cut (in situ)", _num(total.cut), "%s&sup3;" % u, "cut"))
    parts.append(_card("Fill (compacted)", _num(total.fill), "%s&sup3;" % u, "fill"))
    parts.append(_card("Surplus" if net >= 0 else "Deficit",
                       _num(abs(net)), "%s&sup3;" % u, "net"))
    parts.append(_card("Area computed", _num(total.area), "%s&sup2;" % u, ""))
    parts.append("</div>")

    if soil is not None:
        parts.append(
            "<p class='sub'>The surplus is stated after applying a shrinkage "
            "factor of <code>%.4f</code>, derived from an in-situ void ratio "
            "of %.3f and a compacted void ratio of %.3f. It is the volume of "
            "in-situ material left over once enough has been excavated to "
            "build the fill.</p>"
            % (soil.shrinkage_factor, soil.e_insitu, soil.e_compacted))

    if result.topsoil_volume:
        parts.append("<p class='sub'>Topsoil stripped to %.3f %s: "
                     "<strong>%s %s&sup3;</strong>, handled separately from the "
                     "earthworks quantities above.</p>"
                     % (soil.topsoil_strip, u, _num(result.topsoil_volume), u))

    # ---------------- issues ----------------
    if result.issues:
        parts.append("<h2>Data quality and warnings</h2>")
        order = {QualityIssue.SEVERITY_ERROR: 0,
                 QualityIssue.SEVERITY_WARNING: 1,
                 QualityIssue.SEVERITY_INFO: 2}
        for issue in sorted(result.issues, key=lambda i: order.get(i.severity, 3)):
            parts.append("<div class='issue %s'><span class='tag'>%s</span>%s</div>"
                         % (issue.severity, issue.severity, _e(issue.message)))

    # ---------------- balance ----------------
    parts.append("<h2>Balance analysis</h2>")
    if result.balance_level is not None:
        parts.append(
            "<p>The site balances at a %s of <strong>%.3f %s</strong>. At that "
            "level the volume excavated is exactly what is needed to build the "
            "fill, allowing for shrinkage.</p>"
            % (result.curve.reference_label.lower(), result.balance_level, u))
    else:
        parts.append(
            "<p>No balancing level exists within the range of ground "
            "elevations - material must be imported or taken away whatever "
            "level is adopted.</p>")
    if result.minimum_movement_level is not None:
        parts.append(
            "<p class='sub'>The level of minimum total earthmoving is %.3f %s. "
            "This is not usually the same as the balance level, and choosing "
            "between them is a cost decision: hauling material off site "
            "against double-handling it on site.</p>"
            % (result.minimum_movement_level, u))

    chart = result.written.get("balance_chart")
    if chart and embed_charts:
        parts.append(_embed_image(chart))
    hyp = result.written.get("hypsometry_chart")
    if hyp and embed_charts:
        parts.append(_embed_image(hyp))

    # ---------------- material ----------------
    if soil is not None:
        parts.append("<h2>Material movement</h2>")
        from .balance import haul_summary
        rows = haul_summary(total, soil)
        if rows:
            table = ["<table><thead><tr><th>Item</th><th class='num'>Quantity</th>"
                     "<th>Unit</th></tr></thead><tbody>"]
            for label, value, unit in rows:
                table.append("<tr><td>%s</td><td class='num'>%s</td><td>%s</td></tr>"
                             % (_e(label), _num(value), _e(unit)))
            table.append("</tbody></table>")
            parts.append("".join(table))
        warn = soil.moisture_warning()
        if warn:
            parts.append("<div class='issue warning'><span class='tag'>moisture"
                         "</span>%s</div>" % _e(warn))

    # ---------------- per feature ----------------
    if len(result.per_feature) > 1:
        parts.append("<h2>Quantities by polygon</h2>")
        head = ["Feature", "Cut (%s&sup3;)" % u, "Fill (%s&sup3;)" % u,
                "Net (%s&sup3;)" % u, "Area (%s&sup2;)" % u,
                "Max cut (%s)" % u, "Max fill (%s)" % u]
        table = ["<table><thead><tr>"
                 + "".join("<th class='num'>%s</th>" % h if i else "<th>%s</th>" % h
                           for i, h in enumerate(head))
                 + "</tr></thead><tbody>"]
        for dense in sorted(result.per_feature):
            r = result.per_feature[dense]
            fid = result.mapping.get(dense, dense)
            table.append(
                "<tr><td>%s</td><td class='num'>%s</td><td class='num'>%s</td>"
                "<td class='num'>%s</td><td class='num'>%s</td>"
                "<td class='num'>%s</td><td class='num'>%s</td></tr>"
                % (_e(fid), _num(r.cut), _num(r.fill), _num(r.net),
                   _num(r.area), _num(r.max_cut), _num(r.max_fill)))
        table.append(
            "<tr class='total'><td>Total</td><td class='num'>%s</td>"
            "<td class='num'>%s</td><td class='num'>%s</td><td class='num'>%s</td>"
            "<td class='num'>%s</td><td class='num'>%s</td></tr>"
            % (_num(total.cut), _num(total.fill), _num(total.net),
               _num(total.area), _num(total.max_cut), _num(total.max_fill)))
        table.append("</tbody></table>")
        parts.append("".join(table))

    # ---------------- verification ----------------
    parts.append("<h2>Verification</h2>")

    if result.cross_validation:
        parts.append("<h3>Interpolation cross-validation</h3>")
        parts.append(
            "<p class='sub'>Ten-fold cross-validation on the survey points. "
            "The RMSE is the typical elevation error of the interpolated "
            "surface, in %s.</p>" % u)
        rows = ["<table><thead><tr><th>Engine</th><th class='num'>RMSE</th>"
                "<th class='num'>MAE</th><th class='num'>Bias</th>"
                "<th class='num'>Max error</th></tr></thead><tbody>"]
        for eid, s in sorted(result.cross_validation.items(),
                             key=lambda kv: kv[1]["rmse"]):
            used = " (used)" if eid == (analysis.engine_id or "") else ""
            rows.append("<tr><td>%s%s</td><td class='num'>%s</td>"
                        "<td class='num'>%s</td><td class='num'>%s</td>"
                        "<td class='num'>%s</td></tr>"
                        % (_e(s["name"]), used, _num(s["rmse"], 3),
                           _num(s["mae"], 3), _num(s["bias"], 3),
                           _num(s["max_abs"], 3)))
        rows.append("</tbody></table>")
        parts.append("".join(rows))

    if result.volume_uncertainty:
        parts.append(
            "<p>Propagating the interpolation error over the site area gives an "
            "indicative volume uncertainty of <strong>&plusmn; %s %s&sup3;</strong> "
            "(about %.1f%% of the total movement). This accounts only for the "
            "interpolation; survey error, material variability and construction "
            "tolerance are additional.</p>"
            % (_num(result.volume_uncertainty), u,
               result.volume_uncertainty / max(total.cut + total.fill, 1e-9) * 100))

    if result.tin_check is not None:
        parts.append("<h3>Independent TIN integration</h3>")
        parts.append(
            "<p class='sub'>The same quantities computed by exact integration "
            "over the Delaunay triangles rather than over the grid. Close "
            "agreement indicates the cell size is adequate.</p>")
        rows = [("Method", "Cut (%s3)" % u, "Fill (%s3)" % u)]
        body = ["<table><thead><tr><th>Method</th><th class='num'>Cut</th>"
                "<th class='num'>Fill</th><th class='num'>Difference</th>"
                "</tr></thead><tbody>"]
        body.append("<tr><td>Grid integration</td><td class='num'>%s</td>"
                    "<td class='num'>%s</td><td class='num'>-</td></tr>"
                    % (_num(total.cut), _num(total.fill)))
        dc = (abs(total.cut - result.tin_check.cut) / total.cut * 100
              if total.cut else 0.0)
        df = (abs(total.fill - result.tin_check.fill) / total.fill * 100
              if total.fill else 0.0)
        body.append("<tr><td>TIN prismatic (exact)</td><td class='num'>%s</td>"
                    "<td class='num'>%s</td><td class='num'>%.2f%% / %.2f%%"
                    "</td></tr>"
                    % (_num(result.tin_check.cut), _num(result.tin_check.fill),
                       dc, df))
        body.append("</tbody></table>")
        parts.append("".join(body))

    if result.convergence:
        rows, verdict = result.convergence
        if rows:
            parts.append("<h3>Grid convergence</h3>")
            body = ["<table><thead><tr><th>Cell size</th><th class='num'>Cut</th>"
                    "<th class='num'>Fill</th></tr></thead><tbody>"]
            for cell, res in rows:
                body.append("<tr><td>%.3f %s</td><td class='num'>%s</td>"
                            "<td class='num'>%s</td></tr>"
                            % (cell, u, _num(res.cut), _num(res.fill)))
            body.append("</tbody></table>")
            parts.append("".join(body))
            if verdict:
                parts.append(
                    "<p class='sub'>%s</p>"
                    % ("The quantities have stabilised: refining the grid "
                       "changes them by less than 1%, so the cell size is "
                       "adequate." if verdict.get("converged") else
                       "The quantities have not stabilised. Refine the cell "
                       "size before issuing these figures."))

    # ---------------- inputs ----------------
    parts.append("<h2>Inputs and settings</h2>")
    parts.append(_rows_table(result.settings_summary))
    parts.append(_rows_table(result.grid.describe()))

    if result.written:
        parts.append("<h3>Files written</h3>")
        parts.append(_rows_table(
            [(k.replace("_", " ").title(), v) for k, v in sorted(result.written.items())],
            headers=("Output", "Path")))

    if notes:
        parts.append("<h2>Notes</h2><p>%s</p>" % _e(notes).replace("\n", "<br>"))

    parts.append(
        "<div class='foot'>Produced with EarthWorkQ for QGIS. Volumes are "
        "computed by numerical integration of a modelled surface and are only "
        "as good as the survey behind them. This report is not a substitute "
        "for review by a competent engineer.</div>")
    parts.append("</body></html>")
    return "".join(parts)


def _card(label, value, unit, cls):
    return ("<div class='card %s'><div class='label'>%s</div>"
            "<div class='value'>%s</div><div class='unit'>%s</div></div>"
            % (cls, _e(label), value, unit))


def write_report(path, result, analysis, **kwargs):
    html_text = build_report(result, analysis, **kwargs)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(html_text)
    return path
